name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '14 1 * * *' # *-*-* 01:14:00 UTC

permissions:
  contents: read

env:
  RUST_BACKTRACE: full

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      RUSTFLAGS: -Dwarnings
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Fmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --workspace
      - name: Doc
        run: cargo doc --workspace

  test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # Keep in sync with Cargo.toml!
        rust: [nightly, beta, stable, "1.63"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Test ${{matrix.rust}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test

  minimal:
    timeout-minutes: 15
    name: Minimal versions on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo generate-lockfile -Z minimal-versions
      - run: cargo check --locked
