name: Future proof tests
on:
  schedule:
    - cron: '52 1 * * 0' # Sun *-*-* 01:52:00 UTC

  workflow_dispatch:

permissions:
  contents: read

env:
  RUST_BACKTRACE: full

jobs:
  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cargo-outdated
        uses: dtolnay/install@cargo-outdated
      - name: cargo-outdated
        run: rm -f Cargo.lock && cargo outdated --exit-code 1
